In [1]:
import cv2 as cv

In [2]:
!pwd

/home/shahan/Desktop/python lesson/Face detection


In [1]:
#reading and showing and image
import cv2 as cv
import sys
img = cv.imread(cv.samples.findFile("ori.jpg"))
if img is None:
    sys.exit("Could not read the image.")
    
#resize and image 
print('Original Dimensions : ',img.shape)
 
scale_percent = 20 # percent of original size
width = int(img.shape[1] * scale_percent / 100)
height = int(img.shape[0] * scale_percent / 100)
dim = (width, height)
# resize image
resized = cv.resize(img, (512,512), interpolation = cv.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)

cv.imshow("Display window", resized)
k = cv.waitKey(0)
if k == ord("s"):
    cv.imwrite("ori_copy.png", resized)
    cv.destroyAllWindows()

Original Dimensions :  (2880, 5120, 3)
Resized Dimensions :  (512, 512, 3)


In [4]:
#Capture video 
import numpy as np
import cv2 as cv
cap = cv.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv.imshow('frame', gray)
    if cv.waitKey(0) == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()

In [5]:
#Save a video 
import numpy as np
import cv2 as cv
cap = cv.VideoCapture(0)
# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc(*'XVID')
out = cv.VideoWriter('out.mp4', fourcc, 20.0, (640,  480))
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.flip(frame, 0)
    # write the flipped frame
    out.write(frame)
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
# Release everything if job is finished
cap.release()
out.release()
cv.destroyAllWindows()

In [6]:
#play a video 
import numpy as np
import cv2 as cv
cap = cv.VideoCapture('out.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    cv.imshow('frame', gray)
    if cv.waitKey(100) == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

In [7]:
#drawing shapes
import numpy as np
import cv2 as cv
# Create a black image
img = np.zeros((512,512,3), np.uint8)
# Draw a diagonal blue line with thickness of 5 px
cv.line(img,(0,0),(511,511),(255,0,0),5)
#rectangle
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)
#circle
cv.circle(img,(447,63), 63, (0,0,255), -1)
#ellipse
cv.ellipse(img,(256,256),(100,50),0,0,180,255,-1)
#polygon
pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
pts = pts.reshape((-1,1,2))
cv.polylines(img,[pts],True,(0,255,255))
#text
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img,'OpenCV',(10,500), font, 4,(255,255,255),2,cv.LINE_AA)

#show
cv.imshow("Display window", img)
k = cv.waitKey(0)
if k == ord("s"):
    #cv.imwrite("ori_copy.png", img)
    cv.destroyAllWindows()

In [9]:
#Adding text to video 
#Capture video 
import numpy as np
import cv2 as cv
import datetime

cap = cv.VideoCapture(0)

#width and height of cap window
print(cap.get(cv.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv.CAP_PROP_FRAME_HEIGHT))

cap.set(3 , 640) #ret = cap.set(cv.CAP_PROP_FRAME_WIDTH,320) and 
cap.set(4 , 480) #ret = cap.set(cv.CAP_PROP_FRAME_HEIGHT,240)

print(cap.get(3))
print(cap.get(4))
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    #gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    
    #Put Text
    font = cv.FONT_HERSHEY_SIMPLEX
    #text = f"Width : {cap.get(3)} and Height : {cap.get(4)}"
    time_ = f"{datetime.datetime.now()}"
    frame = cv.putText(frame, time_, (10,50), font, 1, (0,255,255), 2, cv.LINE_AA)
    
    # Display the resulting frame
    cv.imshow('frame', frame)
    if cv.waitKey(1) & 0xff == ord('q'): #& bit wise AND with 0xff (bin : 11111111) ASCII (bytes of interest)
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()

640.0
480.0
640.0
480.0


In [19]:
#mouse events
import cv2 as cv
import numpy as np

#To list all the events in system related to cv
events = [i for i in dir(cv) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [29]:
#mouse events
import cv2 as cv
import numpy as np

# To list all the events in system related to cv
# events = [i for i in dir(cv) if 'EVENT' in i]
# print(events)

#call back function
def click_event(event, x, y, flags, params):#get the x and y value of the click on the image, WE Get flag and params
        if event == cv.EVENT_LBUTTONDOWN: # on mouse left button down
            print(f"{x} , {y}")
            location = (x,y)
            font = cv.FONT_HERSHEY_SIMPLEX
            str_xy = f"{x},{y}"
            cv.putText(img,str_xy,location,font,0.5,(255,255,0),2)
            #cv.imshow('Image', img)
        if event == cv.EVENT_RBUTTONDOWN:
            blue = img[x,y,0]
            green = img[x,y,1]
            red = img[x,y,2]
            str_BGR = f"{blue},{green},{red}"
            location = (x,y)
            font = cv.FONT_HERSHEY_SIMPLEX
            cv.putText(img,str_BGR,location,font,0.5,(255,255,0),2)
            #cv.imshow('Image', img)
            

# img = np.zeros((512,512,3),np.uint8)
img = cv.imread("ori_copy.png")
#resized = cv.resize(img, (700,700), interpolation = cv.INTER_AREA)

cv.namedWindow('Image')

# To call the call back function and bind it with the image window 
cv.setMouseCallback('Image', click_event)

while(1):
    cv.imshow('Image',img)
    if cv.waitKey(20) & 0xFF == 27:
        break
cv.destroyAllWindows()

454 , 277
287 , 170
599 , 206
756 , 252


In [6]:
#Advanced draw functions
#mouse events
import cv2 as cv
import numpy as np

#call back function
def click_event(event, x, y, flags, params):#get the x and y value of the click on the image, WE Get flag and params
        if event == cv.EVENT_LBUTTONDOWN: # on mouse left button down
            cv.circle(img, (x,y), 3, (0,0,255), -1)
            points.append((x,y))
            if len(points) >= 2:
                cv.line(img, points[-1], points[-2], (255,0,0), 5)
            #cv.imshow('Image', img)
        if event == cv.EVENT_RBUTTONDOWN:
            blue = img[x,y,0]
            green = img[x,y,1]
            red = img[x,y,2]
            cv.circle(img, (x,y), 3, (0,0,255), -1)
            
            #create a new image with the BGR value of the current image on click , in area of click.
            new_coloured_image = np.zeros((512,512,3), np.uint8)
            
            new_coloured_image[:] = [blue, green, red]
            print(new_coloured_image[:])
            #b,g,r = cv.split(img)
            #new_coloured_image = cv.merge((b,g,r))
            
            cv.imshow('Colour', new_coloured_image)
    

#img = np.zeros((512,512,3),np.uint8)
img = cv.imread("ori_copy.png")
#resized = cv.resize(img, (700,700), interpolation = cv.INTER_AREA)

cv.namedWindow('Image')
points = []
# To call the call back function and bind it with the image window 
cv.setMouseCallback('Image', click_event)

while(1):
    cv.imshow('Image', img)
    if cv.waitKey(20) & 0xFF == 27:
        break
cv.destroyAllWindows()

[[[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]

 [[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]

 [[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]

 ...

 [[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]

 [[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]

 [[204 104 170]
  [204 104 170]
  [204 104 170]
  ...
  [204 104 170]
  [204 104 170]
  [204 104 170]]]


In [5]:
import numpy as np
import cv2 as cv
drawing = False # true if mouse is pressed
mode = True # if True, draw rectangle. Press 'm' to toggle to curve
ix,iy = -1,-1
# mouse callback function
def draw_circle(event,x,y,flags,param):
    global ix,iy,drawing,mode
    if event == cv.EVENT_LBUTTONDOWN:
        drawing = True
        ix,iy = x,y
    elif event == cv.EVENT_MOUSEMOVE:
        if drawing == True:
            if mode == True:
                cv.rectangle(img,(ix,iy),(x,y),(0,255,0),-1)
            else:
                cv.circle(img,(x,y),5,(0,0,255),-1)
    elif event == cv.EVENT_LBUTTONUP:
        drawing = False
        if mode == True:
            cv.rectangle(img,(ix,iy),(x,y),(0,255,0),-1)
        else:
            cv.circle(img,(x,y),5,(0,0,255),-1)
            
img = np.zeros((512,512,3), np.uint8)
cv.namedWindow('image')
cv.setMouseCallback('image',draw_circle)
while(1):
    cv.imshow('image',img)
    k = cv.waitKey(1) & 0xFF
    if k == ord('m'):
        mode = not mode
    elif k == 27:
        break
cv.destroyAllWindows()


In [1]:
#Track bar 
import numpy as np
import cv2 as cv
def nothing(x):
    pass
# Create a black image, a window
img = np.zeros((300,512,3), np.uint8)
cv.namedWindow('image')
# create trackbars for color change
cv.createTrackbar('R','image',0,255,nothing)
cv.createTrackbar('G','image',0,255,nothing)
cv.createTrackbar('B','image',0,255,nothing)
# create switch for ON/OFF functionality
switch = '0 : OFF \n1 : ON'
cv.createTrackbar(switch, 'image',0,1,nothing)
while(1):
    cv.imshow('image',img)
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
    # get current positions of four trackbars
    r = cv.getTrackbarPos('R','image')
    g = cv.getTrackbarPos('G','image')
    b = cv.getTrackbarPos('B','image')
    s = cv.getTrackbarPos(switch,'image')
    if s == 0:
        img[:] = 0
    else:
        img[:] = [b,g,r]
cv.destroyAllWindows()

In [10]:
#Maths on image , operations
import cv2 as cv

img = cv.imread("ori_copy.png")

print(img.shape) #returns a tuple containing rows,columns, and color channel.
print(img.size) #returns the number of pixels accessed.
print(img.dtype) #returns image data type.
b,g,r = cv.split(img)
img = cv.merge((b,g,r))

cv.imshow("Image", img)
cv.waitKey(0)
cv.destroyAllWindows()

(512, 512, 3)
786432
uint8
